# Generated by Django 6.0.3 on 2026-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=200)),
                ('telefon_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contact', models.EmailField(max_length=254, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
