# Generated by Django 6.0.3 on 2026-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
    ]
