# Generated by Django 6.0.3 on 2026-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_approved',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
