# Generated by Django 5.2.3 on 2026-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_bannedrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
